apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sapaicore123
  annotations:
    scenarios.ai.sap.com/description: "code to SAP AI Core"
    scenarios.ai.sap.com/name: "SAPAICore"
    executables.ai.sap.com/description: "Get Business Partners"
    executables.ai.sap.com/name: "Get Business Partners"
  labels:
    scenarios.ai.sap.com/id: "sapai"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/srikanthcr/business-partner-summarizer:latest
      command: ["/bin/sh", "-c"]
      args:
        - "python /SAP Core AI Work/ai.py"
